apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: banking
data:
  DB_HOST: postgres-db-0.postgres-db
  DB_PORT: "5432"
  DB_NAME: "bankingdb" 
  DB_USER: "bankuser"   
  PORT: "3000"
  LOG_LEVEL: "info"
  MAX_LIMIT: "100"